### ISSUE TITLE
Add ./conf/log4j2.json.sample to GIT

### ISSUE THREAD

**Issue by lburaggi** [SignalK/artemis-server#4]
After cloning the project, the first run gives an immediate error due to the missing file ./conf/log4j2.json.sample

**Comment by rob42** [comment]
This project requires the signalk-java project to be present. 

If you are only interested in running the signalk-java artemis server then you should use the install instructions on that project, as it pulls in the compiled artemis-server version on install.

If you are interested in dev on the artemis server, then clone the https://github.com/SignalK/signalk-java project beside the artemis-server project. On linux you can then link the signalk-java/signalk-static dir into the artemis-server root, which provides the UI etc. On windows you may have to copy the files.

To run the artemis-server directly I use eclipse, and set up a bunch or arguments to the run command. I will document these later today (I hope) and commit them. Basically:
```
-Xmx256M  -Dcom.sun.management.jmxremote  -XX:StartFlightRecording -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints  -XX:+HeapDumpOnOutOfMemoryError -Dio.netty.leakDetection.level=ADVANCED -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler --module-path=./target/compiler/graal-sdk.jar:./target/compiler/truffle-api.jar --upgrade-module-path=./target/compiler/compiler.jar
```

**Comment by lburaggi** [comment]
Ok, thank you
