### ISSUE TITLE
NashornPoolFactory throws javax.script.ScriptException on Windows

### ISSUE THREAD

**Issue by lburaggi** [SignalK/artemis-server#6]
When running the server on Windows the following exception is thrown:
NashornPoolFactory - javax.script.ScriptException: <eval>:41841:26 empty range in char class
  'ru-RU': /^[Ð?-Ð¯Ð?]+$/i,
                          ^ in <eval> at line number 41841 at column number 26

This is due to the following (line 55 of NashornPoolFactory ):
`		engine.eval(IOUtils.toString(getIOStream("signalk-parser-nmea0183/dist/bundle.js")));`
I think you should use the `toString(InputStream input, Charset encoding)` call specifing UTF-8 encoding to avoid the error (the default encoding is WIN-1252 on Windows)

**Comment by rob42** [comment]
Best to set it in the commandline apparently. Ive added it to the pom*.xml.

For windows the `<argument>-Dfile.encoding=UTF-8</argument>` may need to be `<argument>-Dfile.encoding="UTF-8"</argument>`. Can you test please.

You can also add this to the startup params to run artemis-server directly in dev. For eclipse you add `-Dfile.encoding=UTF-8` to the VM args in the 'Run configuration'

See 
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4163515
https://stackoverflow.com/questions/5590451/getresourceasstream-what-encoding-is-it-read-as#5590609

**Comment by lburaggi** [comment]
I confirm that -Dfile.encoding=UTF-8 fix the problem on Windows
